In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_csv("./train.csv")
data

,PRODUCT_ID,Y_Class,Y_Quality,TIMESTAMP,LINE,PRODUCT_CODE,X_1,X_2,X_3,X_4,...,X_2866,X_2867,X_2868,X_2869,X_2870,X_2871,X_2872,X_2873,X_2874,X_2875
0,TRAIN_000,1,0.533433,2022-06-13 5:14,T050304,A_31,NaN,NaN,NaN,NaN,...,39.34,40.89,32.56,34.09,77.77,NaN,NaN,NaN,NaN,NaN
1,TRAIN_001,2,0.541819,2022-06-13 5:22,T050307,A_31,NaN,NaN,NaN,NaN,...,38.89,42.82,43.92,35.34,72.55,NaN,NaN,NaN,NaN,NaN
2,TRAIN_002,1,0.531267,2022-06-13 5:30,T050304,A_31,NaN,NaN,NaN,NaN,...,39.19,36.65,42.47,36.53,78.35,NaN,NaN,NaN,NaN,NaN
3,TRAIN_003,2,0.537325,2022-06-13 5:39,T050307,A_31,NaN,NaN,NaN,NaN,...,37.74,39.17,52.17,30.58,71.78,NaN,NaN,NaN,NaN,NaN
4,TRAIN_004,1,0.531590,2022-06-13 5:47,T050304,A_31,NaN,NaN,NaN,NaN,...,38.70,41.89,46.93,33.09,76.97,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
593,TRAIN_593,1,0.526546,2022-09-08 14:30,T100306,T_31,2.0,95.0,0.0,45.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
594,TRAIN_594,0,0.524022,2022-09-08 22:38,T050304,A_31,NaN,NaN,NaN,NaN,...,49.47,53.07,50.89,55.10,66.49,1.0,NaN,NaN,NaN,NaN
595,TRAIN_595,0,0.521289,2022-09-08 22:47,T050304,A_31,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
596,TRAIN_596,1,0.531375,2022-09-08 14:38,T100304,O_31,40.0,94.0,0.0,45.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
597,TRAIN_597,1,0.533702,2022-09-08 14:46,T100306,O_31,21.0,87.0,0.0,45.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
def nan_check(data):
  total=data.isnull().sum().sort_values(ascending=False)
  percent_1 = data.isnull().sum()/data.isnull().count()*100
  percent_2 = (np.round(percent_1, 1)).sort_values(ascending=False)
  missing_data = pd.concat([total, percent_2], axis=1, keys=['Total', '%'])
  return missing_data

x=nan_check(data)
c_1=x['%'] == 100
li=x[c_1].index.to_list()
li

['X_2875',
 'X_2657',
 'X_2650',
 'X_2651',
 'X_2652',
 'X_2653',
 'X_2654',
 'X_2655',
 'X_2656',
 'X_2658',
 'X_2628',
 'X_2659',
 'X_2660',
 'X_2661',
 'X_2662',
 'X_2663',
 'X_2664',
 'X_2665',
 'X_2649',
 'X_2647',
 'X_2646',
 'X_2645',
 'X_2630',
 'X_2631',
 'X_2632',
 'X_2633',
 'X_2634',
 'X_2635',
 'X_2636',
 'X_2637',
 'X_2638',
 'X_2639',
 'X_2640',
 'X_2641',
 'X_2642',
 'X_2643',
 'X_2644',
 'X_2666',
 'X_2667',
 'X_2668',
 'X_2687',
 'X_2689',
 'X_2690',
 'X_2691',
 'X_2692',
 'X_2693',
 'X_2694',
 'X_2695',
 'X_2696',
 'X_2697',
 'X_2698',
 'X_2699',
 'X_937',
 'X_936',
 'X_935',
 'X_934',
 'X_2688',
 'X_2686',
 'X_2669',
 'X_2685',
 'X_2670',
 'X_2671',
 'X_2672',
 'X_2673',
 'X_2674',
 'X_2675',
 'X_2676',
 'X_2677',
 'X_2678',
 'X_2679',
 'X_2680',
 'X_2681',
 'X_2682',
 'X_2683',
 'X_2684',
 'X_2629',
 'X_2648',
 'X_2838',
 'X_2874',
 'X_2873',
 'X_2872',
 'X_2844']

In [ ]:
new_li=[]
for i in li:
  i.replace('\n', '')
  new_li.append(i)
new_li

['X_2875',
 'X_2657',
 'X_2650',
 'X_2651',
 'X_2652',
 'X_2653',
 'X_2654',
 'X_2655',
 'X_2656',
 'X_2658',
 'X_2628',
 'X_2659',
 'X_2660',
 'X_2661',
 'X_2662',
 'X_2663',
 'X_2664',
 'X_2665',
 'X_2649',
 'X_2647',
 'X_2646',
 'X_2645',
 'X_2630',
 'X_2631',
 'X_2632',
 'X_2633',
 'X_2634',
 'X_2635',
 'X_2636',
 'X_2637',
 'X_2638',
 'X_2639',
 'X_2640',
 'X_2641',
 'X_2642',
 'X_2643',
 'X_2644',
 'X_2666',
 'X_2667',
 'X_2668',
 'X_2687',
 'X_2689',
 'X_2690',
 'X_2691',
 'X_2692',
 'X_2693',
 'X_2694',
 'X_2695',
 'X_2696',
 'X_2697',
 'X_2698',
 'X_2699',
 'X_937',
 'X_936',
 'X_935',
 'X_934',
 'X_2688',
 'X_2686',
 'X_2669',
 'X_2685',
 'X_2670',
 'X_2671',
 'X_2672',
 'X_2673',
 'X_2674',
 'X_2675',
 'X_2676',
 'X_2677',
 'X_2678',
 'X_2679',
 'X_2680',
 'X_2681',
 'X_2682',
 'X_2683',
 'X_2684',
 'X_2629',
 'X_2648',
 'X_2838',
 'X_2874',
 'X_2873',
 'X_2872',
 'X_2844']

In [ ]:
for i in li:
  try:
    data.drop(i, axis=1, inplace=True)
  except:
    continue

In [ ]:
data.drop('TIMESTAMP', axis=1, inplace=True)

In [ ]:
data

,PRODUCT_ID,Y_Class,Y_Quality,LINE,PRODUCT_CODE,X_1,X_2,X_3,X_4,X_5,...,X_2862,X_2863,X_2864,X_2865,X_2866,X_2867,X_2868,X_2869,X_2870,X_2871
0,TRAIN_000,1,0.533433,T050304,A_31,NaN,NaN,NaN,NaN,NaN,...,189.0,383.0,368.296296,353.0,39.34,40.89,32.56,34.09,77.77,NaN
1,TRAIN_001,2,0.541819,T050307,A_31,NaN,NaN,NaN,NaN,NaN,...,185.6,383.0,367.735849,353.0,38.89,42.82,43.92,35.34,72.55,NaN
2,TRAIN_002,1,0.531267,T050304,A_31,NaN,NaN,NaN,NaN,NaN,...,165.5,383.0,367.320755,353.0,39.19,36.65,42.47,36.53,78.35,NaN
3,TRAIN_003,2,0.537325,T050307,A_31,NaN,NaN,NaN,NaN,NaN,...,165.8,384.0,369.188679,353.0,37.74,39.17,52.17,30.58,71.78,NaN
4,TRAIN_004,1,0.531590,T050304,A_31,NaN,NaN,NaN,NaN,NaN,...,182.6,383.0,367.351852,352.0,38.70,41.89,46.93,33.09,76.97,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
593,TRAIN_593,1,0.526546,T100306,T_31,2.0,95.0,0.0,45.0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
594,TRAIN_594,0,0.524022,T050304,A_31,NaN,NaN,NaN,NaN,NaN,...,168.7,384.0,369.811321,353.0,49.47,53.07,50.89,55.10,66.49,1.0
595,TRAIN_595,0,0.521289,T050304,A_31,NaN,NaN,NaN,NaN,NaN,...,156.6,383.0,367.018868,352.0,NaN,NaN,NaN,NaN,NaN,1.0
596,TRAIN_596,1,0.531375,T100304,O_31,40.0,94.0,0.0,45.0,11.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
597,TRAIN_597,1,0.533702,T100306,O_31,21.0,87.0,0.0,45.0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
trainY=data.iloc[:,1]
trainY

0      1
1      2
2      1
3      2
4      1
      ..
593    1
594    0
595    0
596    1
597    1
Name: Y_Class, Length: 598, dtype: int64

In [ ]:
new_data=data.replace({'A_31':0, 'O_31':1, 'T_31':2, 'T050304':0, 'T050307':1, 'T100304':2, 'T100306':3, 'T010306':4, 'T010305':5})

In [ ]:
new_data

,PRODUCT_ID,Y_Class,Y_Quality,LINE,PRODUCT_CODE,X_1,X_2,X_3,X_4,X_5,...,X_2862,X_2863,X_2864,X_2865,X_2866,X_2867,X_2868,X_2869,X_2870,X_2871
0,TRAIN_000,1,0.533433,0,0,NaN,NaN,NaN,NaN,NaN,...,189.0,383.0,368.296296,353.0,39.34,40.89,32.56,34.09,77.77,NaN
1,TRAIN_001,2,0.541819,1,0,NaN,NaN,NaN,NaN,NaN,...,185.6,383.0,367.735849,353.0,38.89,42.82,43.92,35.34,72.55,NaN
2,TRAIN_002,1,0.531267,0,0,NaN,NaN,NaN,NaN,NaN,...,165.5,383.0,367.320755,353.0,39.19,36.65,42.47,36.53,78.35,NaN
3,TRAIN_003,2,0.537325,1,0,NaN,NaN,NaN,NaN,NaN,...,165.8,384.0,369.188679,353.0,37.74,39.17,52.17,30.58,71.78,NaN
4,TRAIN_004,1,0.531590,0,0,NaN,NaN,NaN,NaN,NaN,...,182.6,383.0,367.351852,352.0,38.70,41.89,46.93,33.09,76.97,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
593,TRAIN_593,1,0.526546,3,2,2.0,95.0,0.0,45.0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
594,TRAIN_594,0,0.524022,0,0,NaN,NaN,NaN,NaN,NaN,...,168.7,384.0,369.811321,353.0,49.47,53.07,50.89,55.10,66.49,1.0
595,TRAIN_595,0,0.521289,0,0,NaN,NaN,NaN,NaN,NaN,...,156.6,383.0,367.018868,352.0,NaN,NaN,NaN,NaN,NaN,1.0
596,TRAIN_596,1,0.531375,2,1,40.0,94.0,0.0,45.0,11.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
597,TRAIN_597,1,0.533702,3,1,21.0,87.0,0.0,45.0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
trainX=new_data.iloc[:, 3:]
trainX

,LINE,PRODUCT_CODE,X_1,X_2,X_3,X_4,X_5,X_6,X_7,X_8,...,X_2862,X_2863,X_2864,X_2865,X_2866,X_2867,X_2868,X_2869,X_2870,X_2871
0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,189.0,383.0,368.296296,353.0,39.34,40.89,32.56,34.09,77.77,NaN
1,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,185.6,383.0,367.735849,353.0,38.89,42.82,43.92,35.34,72.55,NaN
2,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,165.5,383.0,367.320755,353.0,39.19,36.65,42.47,36.53,78.35,NaN
3,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,165.8,384.0,369.188679,353.0,37.74,39.17,52.17,30.58,71.78,NaN
4,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,182.6,383.0,367.351852,352.0,38.70,41.89,46.93,33.09,76.97,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
593,3,2,2.0,95.0,0.0,45.0,10.0,0.0,50.0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
594,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,168.7,384.0,369.811321,353.0,49.47,53.07,50.89,55.10,66.49,1.0
595,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,156.6,383.0,367.018868,352.0,NaN,NaN,NaN,NaN,NaN,1.0
596,2,1,40.0,94.0,0.0,45.0,11.0,0.0,45.0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
597,3,1,21.0,87.0,0.0,45.0,10.0,0.0,61.0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
from xgboost import XGBClassifier
xgb = XGBClassifier()

In [ ]:
from sklearn.model_selection import GridSearchCV
param_xgb = {"max_depth": [10,30,50],
              "min_child_weight" : [1,3,6,10],
              "n_estimators": [200,300,500,1000]
              }

In [ ]:
gscv_xgb = GridSearchCV (estimator = xgb, param_grid = param_xgb, scoring ='accuracy', cv = 3, refit=True, n_jobs=1, verbose=2)
gscv_xgb.fit(trainX, trainY)

Fitting 3 folds for each of 48 candidates, totalling 144 fits
[CV] END .max_depth=10, min_child_weight=1, n_estimators=200; total time=  31.6s
[CV] END .max_depth=10, min_child_weight=1, n_estimators=200; total time=  32.0s
[CV] END .max_depth=10, min_child_weight=1, n_estimators=200; total time=  32.8s
[CV] END .max_depth=10, min_child_weight=1, n_estimators=300; total time=  39.7s
[CV] END .max_depth=10, min_child_weight=1, n_estimators=300; total time=  48.2s
[CV] END .max_depth=10, min_child_weight=1, n_estimators=300; total time=  38.5s
[CV] END .max_depth=10, min_child_weight=1, n_estimators=500; total time=  49.0s
[CV] END .max_depth=10, min_child_weight=1, n_estimators=500; total time=  51.8s
[CV] END .max_depth=10, min_child_weight=1, n_estimators=500; total time=  50.9s
[CV] END max_depth=10, min_child_weight=1, n_estimators=1000; total time= 1.2min
[CV] END max_depth=10, min_child_weight=1, n_estimators=1000; total time= 1.2min
[CV] END max_depth=10, min_child_weight=1, n_estimators=1000; total time= 1.2min
[CV] END .max_depth=10, min_child_weight=3, n_estimators=200; total time=  26.0s
[CV] END .max_depth=10, min_child_weight=3, n_estimators=200; total time=  27.1s
[CV] END .max_depth=10, min_child_weight=3, n_estimators=200; total time=  26.4s
[CV] END .max_depth=10, min_child_weight=3, n_estimators=300; total time=  32.2s
[CV] END .max_depth=10, min_child_weight=3, n_estimators=300; total time=  34.6s
[CV] END .max_depth=10, min_child_weight=3, n_estimators=300; total time=  32.8s
[CV] END .max_depth=10, min_child_weight=3, n_estimators=500; total time=  41.4s
[CV] END .max_depth=10, min_child_weight=3, n_estimators=500; total time=  44.0s
[CV] END .max_depth=10, min_child_weight=3, n_estimators=500; total time=  42.2s
[CV] END max_depth=10, min_child_weight=3, n_estimators=1000; total time= 1.0min
[CV] END max_depth=10, min_child_weight=3, n_estimators=1000; total time= 1.0min
[CV] END max_depth=10, min_child_weight=3, n_estimators=1000; total time= 1.0min
[CV] END .max_depth=10, min_child_weight=6, n_estimators=200; total time=  24.3s
[CV] END .max_depth=10, min_child_weight=6, n_estimators=200; total time=  24.2s
[CV] END .max_depth=10, min_child_weight=6, n_estimators=200; total time=  23.4s
[CV] END .max_depth=10, min_child_weight=6, n_estimators=300; total time=  28.0s
[CV] END .max_depth=10, min_child_weight=6, n_estimators=300; total time=  30.4s
[CV] END .max_depth=10, min_child_weight=6, n_estimators=300; total time=  28.7s
[CV] END .max_depth=10, min_child_weight=6, n_estimators=500; total time=  37.9s
[CV] END .max_depth=10, min_child_weight=6, n_estimators=500; total time=  39.7s
[CV] END .max_depth=10, min_child_weight=6, n_estimators=500; total time=  39.2s
[CV] END max_depth=10, min_child_weight=6, n_estimators=1000; total time=  57.2s
[CV] END max_depth=10, min_child_weight=6, n_estimators=1000; total time= 1.0min
[CV] END max_depth=10, min_child_weight=6, n_estimators=1000; total time=  55.6s
[CV] END max_depth=10, min_child_weight=10, n_estimators=200; total time=  20.7s
[CV] END max_depth=10, min_child_weight=10, n_estimators=200; total time=  20.6s
[CV] END max_depth=10, min_child_weight=10, n_estimators=200; total time=  21.0s
[CV] END max_depth=10, min_child_weight=10, n_estimators=300; total time=  25.8s
[CV] END max_depth=10, min_child_weight=10, n_estimators=300; total time=  26.8s
[CV] END max_depth=10, min_child_weight=10, n_estimators=300; total time=  26.3s
[CV] END max_depth=10, min_child_weight=10, n_estimators=500; total time=  35.3s
[CV] END max_depth=10, min_child_weight=10, n_estimators=500; total time=  36.5s
[CV] END max_depth=10, min_child_weight=10, n_estimators=500; total time=  36.4s
[CV] END max_depth=10, min_child_weight=10, n_estimators=1000; total time=  55.8s
[CV] END max_depth=10, min_child_weight=10, n_estimators=1000; total time=  54.4s
[CV] END max_depth=10, min_child_weight=10, n_estimators=1000; total time=  54.1s
[CV] END .max_depth=30, min_child_weight=1, n_estimators=200; total time=  32.1s
[CV] END .max_depth=30, min_child_weight=1, n_estimators=200; total time=  34.4s
[CV] END .max_depth=30, min_child_weight=1, n_estimators=200; total time=  31.8s
[CV] END .max_depth=30, min_child_weight=1, n_estimators=300; total time=  40.0s
[CV] END .max_depth=30, min_child_weight=1, n_estimators=300; total time=  41.3s
[CV] END .max_depth=30, min_child_weight=1, n_estimators=300; total time=  39.0s
[CV] END .max_depth=30, min_child_weight=1, n_estimators=500; total time=  52.6s
[CV] END .max_depth=30, min_child_weight=1, n_estimators=500; total time=  52.1s
[CV] END .max_depth=30, min_child_weight=1, n_estimators=500; total time=  50.6s
[CV] END max_depth=30, min_child_weight=1, n_estimators=1000; total time= 1.2min
[CV] END max_depth=30, min_child_weight=1, n_estimators=1000; total time= 1.3min
[CV] END max_depth=30, min_child_weight=1, n_estimators=1000; total time= 1.2min
[CV] END .max_depth=30, min_child_weight=3, n_estimators=200; total time=  26.8s
[CV] END .max_depth=30, min_child_weight=3, n_estimators=200; total time=  30.1s
[CV] END .max_depth=30, min_child_weight=3, n_estimators=200; total time=  26.5s
[CV] END .max_depth=30, min_child_weight=3, n_estimators=300; total time=  32.4s
[CV] END .max_depth=30, min_child_weight=3, n_estimators=300; total time=  33.1s
[CV] END .max_depth=30, min_child_weight=3, n_estimators=300; total time=  32.7s
[CV] END .max_depth=30, min_child_weight=3, n_estimators=500; total time=  41.5s
[CV] END .max_depth=30, min_child_weight=3, n_estimators=500; total time=  45.1s
[CV] END .max_depth=30, min_child_weight=3, n_estimators=500; total time=  42.7s
[CV] END max_depth=30, min_child_weight=3, n_estimators=1000; total time= 1.0min
[CV] END max_depth=30, min_child_weight=3, n_estimators=1000; total time= 1.1min
[CV] END max_depth=30, min_child_weight=3, n_estimators=1000; total time= 1.0min
[CV] END .max_depth=30, min_child_weight=6, n_estimators=200; total time=  23.2s
[CV] END .max_depth=30, min_child_weight=6, n_estimators=200; total time=  24.4s
[CV] END .max_depth=30, min_child_weight=6, n_estimators=200; total time=  22.5s
[CV] END .max_depth=30, min_child_weight=6, n_estimators=300; total time=  29.1s
[CV] END .max_depth=30, min_child_weight=6, n_estimators=300; total time=  29.5s
[CV] END .max_depth=30, min_child_weight=6, n_estimators=300; total time=  28.7s
[CV] END .max_depth=30, min_child_weight=6, n_estimators=500; total time=  37.8s
[CV] END .max_depth=30, min_child_weight=6, n_estimators=500; total time=  41.3s
[CV] END .max_depth=30, min_child_weight=6, n_estimators=500; total time=  39.1s
[CV] END max_depth=30, min_child_weight=6, n_estimators=1000; total time=  56.1s
[CV] END max_depth=30, min_child_weight=6, n_estimators=1000; total time=  58.2s
[CV] END max_depth=30, min_child_weight=6, n_estimators=1000; total time=  55.5s
[CV] END max_depth=30, min_child_weight=10, n_estimators=200; total time=  20.7s
[CV] END max_depth=30, min_child_weight=10, n_estimators=200; total time=  21.9s
[CV] END max_depth=30, min_child_weight=10, n_estimators=200; total time=  20.6s
[CV] END max_depth=30, min_child_weight=10, n_estimators=300; total time=  25.8s
[CV] END max_depth=30, min_child_weight=10, n_estimators=300; total time=  26.6s
[CV] END max_depth=30, min_child_weight=10, n_estimators=300; total time=  26.3s
[CV] END max_depth=30, min_child_weight=10, n_estimators=500; total time=  35.6s
[CV] END max_depth=30, min_child_weight=10, n_estimators=500; total time=  36.8s
[CV] END max_depth=30, min_child_weight=10, n_estimators=500; total time=  36.7s
[CV] END max_depth=30, min_child_weight=10, n_estimators=1000; total time=  55.1s
[CV] END max_depth=30, min_child_weight=10, n_estimators=1000; total time=  55.6s
[CV] END max_depth=30, min_child_weight=10, n_estimators=1000; total time=  53.5s
[CV] END .max_depth=50, min_child_weight=1, n_estimators=200; total time=  32.9s
[CV] END .max_depth=50, min_child_weight=1, n_estimators=200; total time=  33.7s
[CV] END .max_depth=50, min_child_weight=1, n_estimators=200; total time=  32.9s
[CV] END .max_depth=50, min_child_weight=1, n_estimators=300; total time=  40.3s
[CV] END .max_depth=50, min_child_weight=1, n_estimators=300; total time=  41.1s
[CV] END .max_depth=50, min_child_weight=1, n_estimators=300; total time=  39.2s
[CV] END .max_depth=50, min_child_weight=1, n_estimators=500; total time=  50.7s
[CV] END .max_depth=50, min_child_weight=1, n_estimators=500; total time=  52.7s
[CV] END .max_depth=50, min_child_weight=1, n_estimators=500; total time=  52.7s
[CV] END max_depth=50, min_child_weight=1, n_estimators=1000; total time= 1.2min
[CV] END max_depth=50, min_child_weight=1, n_estimators=1000; total time= 1.3min
[CV] END max_depth=50, min_child_weight=1, n_estimators=1000; total time= 1.2min
[CV] END .max_depth=50, min_child_weight=3, n_estimators=200; total time=  27.4s
[CV] END .max_depth=50, min_child_weight=3, n_estimators=200; total time=  28.2s
[CV] END .max_depth=50, min_child_weight=3, n_estimators=200; total time=  26.6s
[CV] END .max_depth=50, min_child_weight=3, n_estimators=300; total time=  32.4s
[CV] END .max_depth=50, min_child_weight=3, n_estimators=300; total time=  34.5s
[CV] END .max_depth=50, min_child_weight=3, n_estimators=300; total time=  31.9s
[CV] END .max_depth=50, min_child_weight=3, n_estimators=500; total time=  42.6s
[CV] END .max_depth=50, min_child_weight=3, n_estimators=500; total time=  45.2s
[CV] END .max_depth=50, min_child_weight=3, n_estimators=500; total time=  43.8s
[CV] END max_depth=50, min_child_weight=3, n_estimators=1000; total time= 1.0min
[CV] END max_depth=50, min_child_weight=3, n_estimators=1000; total time= 1.1min
[CV] END max_depth=50, min_child_weight=3, n_estimators=1000; total time= 1.0min
[CV] END .max_depth=50, min_child_weight=6, n_estimators=200; total time=  23.7s
[CV] END .max_depth=50, min_child_weight=6, n_estimators=200; total time=  24.6s
[CV] END .max_depth=50, min_child_weight=6, n_estimators=200; total time=  23.5s
[CV] END .max_depth=50, min_child_weight=6, n_estimators=300; total time=  28.1s
[CV] END .max_depth=50, min_child_weight=6, n_estimators=300; total time=  30.5s
[CV] END .max_depth=50, min_child_weight=6, n_estimators=300; total time=  28.8s
[CV] END .max_depth=50, min_child_weight=6, n_estimators=500; total time=  37.9s
[CV] END .max_depth=50, min_child_weight=6, n_estimators=500; total time=  39.7s
[CV] END .max_depth=50, min_child_weight=6, n_estimators=500; total time=  40.2s
[CV] END max_depth=50, min_child_weight=6, n_estimators=1000; total time=  57.4s
[CV] END max_depth=50, min_child_weight=6, n_estimators=1000; total time=  57.8s
[CV] END max_depth=50, min_child_weight=6, n_estimators=1000; total time=  57.1s
[CV] END max_depth=50, min_child_weight=10, n_estimators=200; total time=  20.1s
[CV] END max_depth=50, min_child_weight=10, n_estimators=200; total time=  22.4s
[CV] END max_depth=50, min_child_weight=10, n_estimators=200; total time=  21.4s
[CV] END max_depth=50, min_child_weight=10, n_estimators=300; total time=  26.0s
[CV] END max_depth=50, min_child_weight=10, n_estimators=300; total time=  26.9s
[CV] END max_depth=50, min_child_weight=10, n_estimators=300; total time=  26.6s
[CV] END max_depth=50, min_child_weight=10, n_estimators=500; total time=  35.9s
[CV] END max_depth=50, min_child_weight=10, n_estimators=500; total time=  37.1s
[CV] END max_depth=50, min_child_weight=10, n_estimators=500; total time=  37.0s
[CV] END max_depth=50, min_child_weight=10, n_estimators=1000; total time=  55.5s
[CV] END max_depth=50, min_child_weight=10, n_estimators=1000; total time=  55.6s
[CV] END max_depth=50, min_child_weight=10, n_estimators=1000; total time=  55.4s

GridSearchCV(cv=3, estimator=XGBClassifier(), n_jobs=1,
             param_grid={'max_depth': [10, 30, 50],
                         'min_child_weight': [1, 3, 6, 10],
                         'n_estimators': [200, 300, 500, 1000]},
             scoring='accuracy', verbose=2)

In [ ]:
print('XGB 파라미터: ', gscv_xgb.best_params_)
print('XGB 예측 정확도: {:.4f}'.format(gscv_xgb.best_score_))

XGB 파라미터:  {'max_depth': 30, 'min_child_weight': 6, 'n_estimators': 200}
XGB 예측 정확도: 0.6372

In [ ]:
data_test = pd.read_csv("./test.csv")
for i in li:
  try:
    data_test.drop(i, axis=1, inplace=True)
  except:
    continue
data_test.drop('TIMESTAMP', axis=1, inplace=True)
new_data_test=data_test.replace({'A_31':0, 'O_31':1, 'T_31':2, 'T050304':0, 'T050307':1, 'T100304':2, 'T100306':3, 'T010306':4, 'T010305':5})
testX=new_data_test.iloc[:,1:]
testX

,LINE,PRODUCT_CODE,X_1,X_2,X_3,X_4,X_5,X_6,X_7,X_8,...,X_2862,X_2863,X_2864,X_2865,X_2866,X_2867,X_2868,X_2869,X_2870,X_2871
0,3,2,2.0,94.0,0.0,45.0,10.0,0.0,51.0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,2,2.0,93.0,0.0,45.0,11.0,0.0,45.0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,2,2.0,95.0,0.0,45.0,11.0,0.0,45.0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,183.8,467.0,444.192308,423.0,NaN,NaN,NaN,NaN,NaN,NaN
4,4,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,179.7,465.0,443.211539,423.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305,3,2,2.0,91.0,0.0,45.0,10.0,0.0,51.0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
306,2,2,2.0,96.0,0.0,45.0,11.0,0.0,45.0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307,3,2,2.0,91.0,0.0,45.0,10.0,0.0,50.0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
308,3,2,2.0,95.0,0.0,45.0,10.0,0.0,51.0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
309,3,2,2.0,87.0,0.0,45.0,10.0,0.0,51.0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
testX

,PRODUCT_CODE,X_1,X_2,X_3,X_4,X_5,X_6,X_7,X_8,X_9,...,X_2862,X_2863,X_2864,X_2865,X_2866,X_2867,X_2868,X_2869,X_2870,X_2871
0,2,2.0,94.0,0.0,45.0,10.0,0.0,51.0,10.0,52.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,2.0,93.0,0.0,45.0,11.0,0.0,45.0,10.0,31.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,2.0,95.0,0.0,45.0,11.0,0.0,45.0,10.0,31.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,183.8,467.0,444.192308,423.0,NaN,NaN,NaN,NaN,NaN,NaN
4,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,179.7,465.0,443.211539,423.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305,2,2.0,91.0,0.0,45.0,10.0,0.0,51.0,10.0,52.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
306,2,2.0,96.0,0.0,45.0,11.0,0.0,45.0,10.0,31.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307,2,2.0,91.0,0.0,45.0,10.0,0.0,50.0,10.0,52.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
308,2,2.0,95.0,0.0,45.0,10.0,0.0,51.0,10.0,52.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
309,2,2.0,87.0,0.0,45.0,10.0,0.0,51.0,10.0,52.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
from sklearn.metrics import accuracy_score
em=gscv_xgb.best_estimator_
pred = em.predict(testX)
pred

array([1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 2, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 0, 0, 0, 2, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 1, 1, 2,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1])

In [ ]:
pred

array([1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 2, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 0, 0, 0, 2, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 1, 1, 2,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1])

In [ ]:
pred_val=pred.tolist()

In [ ]:
pred_num=data_test.iloc[:, 0]
pred_num

0      TEST_000
1      TEST_001
2      TEST_002
3      TEST_003
4      TEST_004
         ...
305    TEST_305
306    TEST_306
307    TEST_307
308    TEST_308
309    TEST_309
Name: PRODUCT_ID, Length: 310, dtype: object

In [ ]:
predicted=pd.DataFrame(pred_val, columns=['Y_Class'])
predicted

     Y_Class
0          1
1          1
2          1
3          1
4          1
..       ...
305        1
306        1
307        1
308        1
309        1

[310 rows x 1 columns]

In [ ]:
final=pd.concat([pred_num, predicted], axis=1)
final

    PRODUCT_ID  Y_Class
0     TEST_000        1
1     TEST_001        1
2     TEST_002        1
3     TEST_003        1
4     TEST_004        1
..         ...      ...
305   TEST_305        1
306   TEST_306        1
307   TEST_307        1
308   TEST_308        1
309   TEST_309        1

[310 rows x 2 columns]

In [ ]:
final.to_csv('submission.csv', sep=',')